-- Invoice Collector — complete schema
--
-- Generated by scripts/build-schema.ts. Do not edit by hand; edit the
-- source migrations and regenerate.
--
-- FRESH INSTALLS ONLY. The first section drops the core tables before
-- recreating them. Running this against a database that holds real data
-- will destroy it. To update an existing database, apply only the
-- individual migrations it is missing — run scripts/check-migrations.ts
-- to see which those are.


-- ==========================================================================
-- supabase/migrations/supabase-schema.sql
-- ==========================================================================

-- Invoice Collector Database Schema
-- Run this in Supabase SQL Editor

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================================
-- DROP EXISTING TABLES IF THEY EXIST (Fresh start)
-- ============================================================================
DROP TABLE IF EXISTS user_feedback CASCADE;
DROP TABLE IF EXISTS sender_reputation CASCADE;
DROP TABLE IF EXISTS sync_jobs CASCADE;
DROP TABLE IF EXISTS documents CASCADE;
DROP TABLE IF EXISTS user_settings CASCADE;
DROP TABLE IF EXISTS gmail_accounts CASCADE;

-- Drop existing types
DROP TYPE IF EXISTS feedback_action CASCADE;
DROP TYPE IF EXISTS sync_status CASCADE;
DROP TYPE IF EXISTS document_status CASCADE;
DROP TYPE IF EXISTS document_classification CASCADE;

-- ============================================================================
-- CREATE ENUMS FIRST
-- ============================================================================

-- Create ENUMs before tables
CREATE TYPE document_classification AS ENUM ('invoice', 'credit_note', 'unclassified');
CREATE TYPE document_status AS ENUM ('pending', 'approved', 'rejected');
CREATE TYPE sync_status AS ENUM ('running', 'completed', 'failed');
CREATE TYPE feedback_action AS ENUM ('approved', 'rejected', 'reclassified');

-- ============================================================================
-- TABLES
-- ============================================================================

-- Gmail Accounts Table
CREATE TABLE gmail_accounts (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  access_token TEXT NOT NULL,
  refresh_token TEXT NOT NULL,
  token_expiry TIMESTAMPTZ NOT NULL,
  is_primary BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),

  UNIQUE(user_id) -- MVP: Only one account per user
);

-- User Settings Table
CREATE TABLE user_settings (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE UNIQUE,
  drive_folder_id TEXT,
  drive_folder_name TEXT,
  drive_folder_path TEXT,
  sync_days_back INTEGER DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Documents Table
CREATE TABLE documents (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  gmail_account_id UUID NOT NULL REFERENCES gmail_accounts(id) ON DELETE CASCADE,
  email_message_id TEXT NOT NULL,
  file_hash TEXT NOT NULL,
  subject TEXT,
  sender TEXT,
  sender_domain TEXT,
  received_date TIMESTAMPTZ NOT NULL,
  filename TEXT NOT NULL,
  original_classification document_classification NOT NULL,
  final_classification document_classification NOT NULL,
  confidence_score DECIMAL(5,4),
  was_reclassified BOOLEAN DEFAULT false,
  status document_status DEFAULT 'pending',
  drive_file_id TEXT,
  drive_folder_path TEXT,
  processed_at TIMESTAMPTZ DEFAULT NOW(),
  approved_at TIMESTAMPTZ,
  rejected_at TIMESTAMPTZ,

  UNIQUE(user_id, email_message_id)
);

-- Create indexes for faster queries
CREATE INDEX IF NOT EXISTS idx_documents_user_status ON documents(user_id, status);
CREATE INDEX IF NOT EXISTS idx_documents_sender_domain ON documents(sender_domain);
CREATE INDEX IF NOT EXISTS idx_documents_received_date ON documents(received_date DESC);

-- Sync Jobs Table
CREATE TABLE sync_jobs (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  gmail_account_id UUID NOT NULL REFERENCES gmail_accounts(id) ON DELETE CASCADE,
  status sync_status DEFAULT 'running',
  sync_from_date TIMESTAMPTZ NOT NULL,
  sync_to_date TIMESTAMPTZ NOT NULL,
  emails_scanned INTEGER DEFAULT 0,
  documents_found INTEGER DEFAULT 0,
  duplicates_skipped INTEGER DEFAULT 0,
  started_at TIMESTAMPTZ DEFAULT NOW(),
  completed_at TIMESTAMPTZ,
  error_message TEXT
);

-- User Feedback Table (Learning)
CREATE TABLE user_feedback (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  document_id UUID NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
  action feedback_action NOT NULL,
  original_classification document_classification,
  new_classification document_classification,
  sender_domain TEXT,
  feedback_at TIMESTAMPTZ DEFAULT NOW()
);

-- Sender Reputation Table
CREATE TABLE sender_reputation (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  sender_domain TEXT NOT NULL,
  approval_count INTEGER DEFAULT 0,
  rejection_count INTEGER DEFAULT 0,
  reputation_score DECIMAL(10,2) DEFAULT 0,
  is_trusted BOOLEAN DEFAULT false,
  is_blocked BOOLEAN DEFAULT false,
  last_interaction TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  UNIQUE(user_id, sender_domain)
);

-- ============================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ============================================================================

-- Enable RLS on all tables
ALTER TABLE gmail_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE sync_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE sender_reputation ENABLE ROW LEVEL SECURITY;

-- Gmail Accounts Policies
DROP POLICY IF EXISTS "Users can manage own Gmail account" ON gmail_accounts;
CREATE POLICY "Users can manage own Gmail account"
  ON gmail_accounts FOR ALL
  USING (auth.uid() = user_id);

-- User Settings Policies
DROP POLICY IF EXISTS "Users can manage own settings" ON user_settings;
CREATE POLICY "Users can manage own settings"
  ON user_settings FOR ALL
  USING (auth.uid() = user_id);

-- Documents Policies
DROP POLICY IF EXISTS "Users can view own documents" ON documents;
CREATE POLICY "Users can view own documents"
  ON documents FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own documents" ON documents;
CREATE POLICY "Users can insert own documents"
  ON documents FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own documents" ON documents;
CREATE POLICY "Users can update own documents"
  ON documents FOR UPDATE
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete own documents" ON documents;
CREATE POLICY "Users can delete own documents"
  ON documents FOR DELETE
  USING (auth.uid() = user_id);

-- Sync Jobs Policies
DROP POLICY IF EXISTS "Users can view own sync jobs" ON sync_jobs;
CREATE POLICY "Users can view own sync jobs"
  ON sync_jobs FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own sync jobs" ON sync_jobs;
CREATE POLICY "Users can insert own sync jobs"
  ON sync_jobs FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own sync jobs" ON sync_jobs;
CREATE POLICY "Users can update own sync jobs"
  ON sync_jobs FOR UPDATE
  USING (auth.uid() = user_id);

-- User Feedback Policies
DROP POLICY IF EXISTS "Users can manage own feedback" ON user_feedback;
CREATE POLICY "Users can manage own feedback"
  ON user_feedback FOR ALL
  USING (auth.uid() = user_id);

-- Sender Reputation Policies
DROP POLICY IF EXISTS "Users can manage own reputation data" ON sender_reputation;
CREATE POLICY "Users can manage own reputation data"
  ON sender_reputation FOR ALL
  USING (auth.uid() = user_id);

-- ============================================================================
-- DATABASE FUNCTIONS
-- ============================================================================

-- Function to automatically update sender reputation
CREATE OR REPLACE FUNCTION update_sender_reputation()
RETURNS TRIGGER AS $$
BEGIN
  -- Insert or update sender reputation
  INSERT INTO sender_reputation (
    user_id,
    sender_domain,
    approval_count,
    rejection_count,
    reputation_score,
    is_trusted,
    is_blocked,
    last_interaction,
    updated_at
  )
  VALUES (
    NEW.user_id,
    NEW.sender_domain,
    CASE WHEN NEW.action = 'approved' THEN 1 ELSE 0 END,
    CASE WHEN NEW.action = 'rejected' THEN 1 ELSE 0 END,
    CASE WHEN NEW.action = 'approved' THEN 1 ELSE -1 END,
    false,
    false,
    NOW(),
    NOW()
  )
  ON CONFLICT (user_id, sender_domain)
  DO UPDATE SET
    approval_count = sender_reputation.approval_count +
      CASE WHEN NEW.action = 'approved' THEN 1 ELSE 0 END,
    rejection_count = sender_reputation.rejection_count +
      CASE WHEN NEW.action = 'rejected' THEN 1 ELSE 0 END,
    reputation_score = (sender_reputation.approval_count +
      CASE WHEN NEW.action = 'approved' THEN 1 ELSE 0 END) -
      (sender_reputation.rejection_count +
      CASE WHEN NEW.action = 'rejected' THEN 1 ELSE 0 END),
    is_trusted = (sender_reputation.approval_count +
      CASE WHEN NEW.action = 'approved' THEN 1 ELSE 0 END) >= 3,
    is_blocked = (sender_reputation.rejection_count +
      CASE WHEN NEW.action = 'rejected' THEN 1 ELSE 0 END) >= 2,
    last_interaction = NOW(),
    updated_at = NOW();

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to auto-update reputation on feedback
DROP TRIGGER IF EXISTS trigger_update_sender_reputation ON user_feedback;
CREATE TRIGGER trigger_update_sender_reputation
  AFTER INSERT ON user_feedback
  FOR EACH ROW
  EXECUTE FUNCTION update_sender_reputation();

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger for user_settings
DROP TRIGGER IF EXISTS update_user_settings_updated_at ON user_settings;
CREATE TRIGGER update_user_settings_updated_at
  BEFORE UPDATE ON user_settings
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Trigger for sender_reputation (on manual updates)
DROP TRIGGER IF EXISTS update_sender_reputation_updated_at ON sender_reputation;
CREATE TRIGGER update_sender_reputation_updated_at
  BEFORE UPDATE ON sender_reputation
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- DONE!
-- ============================================================================

-- Verify tables were created
SELECT
  'gmail_accounts' as table_name,
  (SELECT COUNT(*) FROM gmail_accounts) as row_count
UNION ALL
SELECT 'user_settings', (SELECT COUNT(*) FROM user_settings)
UNION ALL
SELECT 'documents', (SELECT COUNT(*) FROM documents)
UNION ALL
SELECT 'sync_jobs', (SELECT COUNT(*) FROM sync_jobs)
UNION ALL
SELECT 'user_feedback', (SELECT COUNT(*) FROM user_feedback)
UNION ALL
SELECT 'sender_reputation', (SELECT COUNT(*) FROM sender_reputation);

-- ==========================================================================
-- supabase/migrations/003_add_notifications.sql
-- ==========================================================================

-- Add notification settings to user_settings table
ALTER TABLE user_settings
ADD COLUMN IF NOT EXISTS auto_sync_enabled BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS email_notifications_enabled BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS notification_email TEXT,
ADD COLUMN IF NOT EXISTS last_auto_sync_at TIMESTAMP WITH TIME ZONE;

-- Add comment to explain columns
COMMENT ON COLUMN user_settings.auto_sync_enabled IS 'Enable automatic email syncing via cron job';
COMMENT ON COLUMN user_settings.email_notifications_enabled IS 'Send email notifications when new documents are found';
COMMENT ON COLUMN user_settings.notification_email IS 'Email address for notifications (defaults to user email)';
COMMENT ON COLUMN user_settings.last_auto_sync_at IS 'Timestamp of last successful auto-sync';

-- ==========================================================================
-- supabase/migrations/004_add_webhook_url.sql
-- ==========================================================================

-- Add webhook_url column to user_settings table
-- This allows admins to configure the n8n webhook endpoint for invoice processing

ALTER TABLE user_settings
ADD COLUMN IF NOT EXISTS webhook_url TEXT DEFAULT 'https://n8n.rfrancisco.io/webhook/invoice-processor';

-- Add comment for documentation
COMMENT ON COLUMN user_settings.webhook_url IS 'External webhook URL for automated invoice data extraction (n8n integration)';

-- ==========================================================================
-- supabase/migrations/005_add_invoice_fields.sql
-- ==========================================================================

-- Add invoice data fields to documents table
-- These fields store structured data extracted from PDFs via webhook

ALTER TABLE documents
ADD COLUMN IF NOT EXISTS invoice_number TEXT,
ADD COLUMN IF NOT EXISTS issue_date DATE,
ADD COLUMN IF NOT EXISTS supplier_name TEXT,
ADD COLUMN IF NOT EXISTS supplier_vat_number TEXT,
ADD COLUMN IF NOT EXISTS total_without_vat NUMERIC(10,2),
ADD COLUMN IF NOT EXISTS total_vat NUMERIC(10,2),
ADD COLUMN IF NOT EXISTS invoice_total NUMERIC(10,2),
ADD COLUMN IF NOT EXISTS currency TEXT,
ADD COLUMN IF NOT EXISTS numb_pages INTEGER,
ADD COLUMN IF NOT EXISTS document_type TEXT,
ADD COLUMN IF NOT EXISTS webhook_processed_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS webhook_error TEXT;

-- Add comments for documentation
COMMENT ON COLUMN documents.invoice_number IS 'Invoice number extracted from PDF';
COMMENT ON COLUMN documents.issue_date IS 'Invoice issue date extracted from PDF';
COMMENT ON COLUMN documents.supplier_name IS 'Supplier/vendor name extracted from PDF';
COMMENT ON COLUMN documents.supplier_vat_number IS 'Supplier VAT/tax ID extracted from PDF';
COMMENT ON COLUMN documents.total_without_vat IS 'Invoice subtotal (without VAT/tax)';
COMMENT ON COLUMN documents.total_vat IS 'Total VAT/tax amount';
COMMENT ON COLUMN documents.invoice_total IS 'Total invoice amount (including VAT)';
COMMENT ON COLUMN documents.currency IS 'Currency code (EUR, USD, etc.)';
COMMENT ON COLUMN documents.numb_pages IS 'Number of pages in the PDF';
COMMENT ON COLUMN documents.document_type IS 'Document type returned by webhook (invoice, credit_note, etc.)';
COMMENT ON COLUMN documents.webhook_processed_at IS 'Timestamp when webhook successfully processed the document';
COMMENT ON COLUMN documents.webhook_error IS 'Error message if webhook processing failed';

-- Create index on invoice_number for faster searches
CREATE INDEX IF NOT EXISTS idx_documents_invoice_number ON documents(invoice_number);

-- Create index on supplier_name for faster searches
CREATE INDEX IF NOT EXISTS idx_documents_supplier_name ON documents(supplier_name);

-- Create index on issue_date for date range queries
CREATE INDEX IF NOT EXISTS idx_documents_issue_date ON documents(issue_date);

-- Create index on webhook_error to quickly find failed processing
CREATE INDEX IF NOT EXISTS idx_documents_webhook_error ON documents(webhook_error) WHERE webhook_error IS NOT NULL;

-- ==========================================================================
-- supabase/migrations/006_fix_existing_classifications.sql
-- ==========================================================================

-- Fix existing document classifications based on webhook document_type
-- This updates records that were processed before the classification logic was fixed

-- Update supplier_invoice -> invoice
UPDATE documents
SET
  original_classification = 'invoice',
  final_classification = 'invoice',
  confidence_score = 1.0
WHERE
  document_type = 'supplier_invoice'
  AND final_classification = 'unclassified';

-- Update credit_note (if any exist)
UPDATE documents
SET
  original_classification = 'credit_note',
  final_classification = 'credit_note',
  confidence_score = 1.0
WHERE
  document_type = 'credit_note'
  AND final_classification = 'unclassified';

-- Add comment for documentation
COMMENT ON COLUMN documents.document_type IS 'Document type returned by webhook: supplier_invoice maps to invoice classification, credit_note maps to credit_note classification';

-- ==========================================================================
-- supabase/migrations/007_mark_failed_webhooks_for_reprocessing.sql
-- ==========================================================================

-- Mark documents with null document_type as needing reprocessing
-- This applies to documents that were processed before the webhook parsing fix
-- We'll add a webhook_error so they can be identified for manual reprocessing

UPDATE documents
SET
  webhook_error = 'Webhook response parsing failed - needs reprocessing'
WHERE
  document_type IS NULL
  AND webhook_processed_at IS NULL
  AND status = 'pending'
  AND final_classification = 'unclassified';

-- Add comment for documentation
COMMENT ON COLUMN documents.webhook_error IS 'Error message if webhook processing failed. Documents with this field populated may need reprocessing.';

-- ==========================================================================
-- supabase/migrations/008_add_gmail_label_setting.sql
-- ==========================================================================

-- Add Gmail label configuration to user_settings
-- This allows users to customize the label applied to synced emails

ALTER TABLE user_settings
ADD COLUMN IF NOT EXISTS gmail_sync_label TEXT DEFAULT 'Invoice Collector - Synced';

-- Add option to archive synced emails
ALTER TABLE user_settings
ADD COLUMN IF NOT EXISTS archive_synced_emails BOOLEAN DEFAULT false;

-- Add comments for documentation
COMMENT ON COLUMN user_settings.gmail_sync_label IS 'Gmail label to apply to emails after they have been synced. Default: "Invoice Collector - Synced"';
COMMENT ON COLUMN user_settings.archive_synced_emails IS 'If true, emails will be archived (removed from inbox) after syncing. Default: false';

-- ==========================================================================
-- supabase/migrations/009_add_subscription_tier.sql
-- ==========================================================================

-- Add subscription tier for sync frequency control
-- Free users: 2 syncs per day (720 minutes = 12 hours)
-- Paid users: sync every 15 minutes

-- Create enum type for subscription tiers
DO $$ BEGIN
  CREATE TYPE subscription_tier AS ENUM ('free', 'paid');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

-- Add subscription tier column
ALTER TABLE user_settings
ADD COLUMN IF NOT EXISTS subscription_tier TEXT DEFAULT 'free' CHECK (subscription_tier IN ('free', 'paid'));

-- Add sync frequency in minutes (calculated based on tier)
-- Free: 720 minutes (12 hours, 2x per day)
-- Paid: 15 minutes
ALTER TABLE user_settings
ADD COLUMN IF NOT EXISTS sync_frequency_minutes INTEGER DEFAULT 720;

-- Add comments for documentation
COMMENT ON COLUMN user_settings.subscription_tier IS 'User subscription tier: free (2 syncs/day) or paid (every 15 min)';
COMMENT ON COLUMN user_settings.sync_frequency_minutes IS 'Sync frequency in minutes. Free: 720 (12h), Paid: 15';

-- Create function to automatically set sync frequency based on tier
CREATE OR REPLACE FUNCTION set_sync_frequency_from_tier()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.subscription_tier = 'paid' THEN
    NEW.sync_frequency_minutes := 15;
  ELSE
    NEW.sync_frequency_minutes := 720;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger to auto-update sync frequency when tier changes
DROP TRIGGER IF EXISTS update_sync_frequency ON user_settings;
CREATE TRIGGER update_sync_frequency
  BEFORE INSERT OR UPDATE OF subscription_tier ON user_settings
  FOR EACH ROW
  EXECUTE FUNCTION set_sync_frequency_from_tier();

-- ==========================================================================
-- supabase/migrations/010_add_profiles_and_roles.sql
-- ==========================================================================

-- Migration 010: Add Profiles Table and User Roles
-- This creates a profiles table for user metadata and role management

-- Create user_role enum
DO $$ BEGIN
  CREATE TYPE user_role AS ENUM ('user', 'admin');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

-- Create profiles table (extends auth.users)
CREATE TABLE IF NOT EXISTS profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  full_name TEXT,
  avatar_url TEXT,
  role user_role DEFAULT 'user',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "Users can view own profile" ON profiles;
DROP POLICY IF EXISTS "Users can update own profile" ON profiles;
DROP POLICY IF EXISTS "Users can insert own profile" ON profiles;
DROP POLICY IF EXISTS "Service role can manage all profiles" ON profiles;

-- Users can view their own profile
CREATE POLICY "Users can view own profile"
  ON profiles FOR SELECT
  USING (auth.uid() = id);

-- Users can update their own profile (but cannot change their role)
CREATE POLICY "Users can update own profile"
  ON profiles FOR UPDATE
  USING (auth.uid() = id)
  WITH CHECK (
    auth.uid() = id
    AND role = (SELECT role FROM profiles WHERE id = auth.uid())
  );

-- Users can insert their own profile (for manual creation if trigger fails)
CREATE POLICY "Users can insert own profile"
  ON profiles FOR INSERT
  WITH CHECK (auth.uid() = id);

-- Function to automatically create profile on user signup
CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, avatar_url)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.raw_user_meta_data->>'name'),
    NEW.raw_user_meta_data->>'avatar_url'
  )
  ON CONFLICT (id) DO UPDATE SET
    email = EXCLUDED.email,
    full_name = COALESCE(EXCLUDED.full_name, profiles.full_name),
    avatar_url = COALESCE(EXCLUDED.avatar_url, profiles.avatar_url),
    updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger for new user signup
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION handle_new_user();

-- Trigger to update updated_at on profile changes
DROP TRIGGER IF EXISTS update_profiles_updated_at ON profiles;
CREATE TRIGGER update_profiles_updated_at
  BEFORE UPDATE ON profiles
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Backfill profiles for existing users
INSERT INTO profiles (id, email, full_name)
SELECT id, email, raw_user_meta_data->>'full_name'
FROM auth.users
WHERE id NOT IN (SELECT id FROM profiles)
ON CONFLICT (id) DO NOTHING;

-- Add comments
COMMENT ON TABLE profiles IS 'User profiles with role management';
COMMENT ON COLUMN profiles.role IS 'User role: user (default) or admin';

-- ==========================================================================
-- supabase/migrations/011_admin_rls_policies.sql
-- ==========================================================================

-- Migration 011: Admin RLS Policies
-- Admins can view sync_jobs (logs) but NOT user documents, settings, or tokens

-- Helper function to check if current user is admin
CREATE OR REPLACE FUNCTION is_admin()
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM profiles
    WHERE id = auth.uid() AND role = 'admin'
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER STABLE;

-- =====================================================
-- SYNC_JOBS: Admins can READ all (for monitoring)
-- =====================================================

-- Add policy for admins to view all sync jobs
DROP POLICY IF EXISTS "Admins can view all sync jobs" ON sync_jobs;
CREATE POLICY "Admins can view all sync jobs"
  ON sync_jobs FOR SELECT
  USING (is_admin());

-- =====================================================
-- ADMIN STATS VIEW (aggregate data only, no PII)
-- =====================================================

-- Drop view if exists
DROP VIEW IF EXISTS admin_stats;

-- Create admin stats view with aggregate metrics only
CREATE VIEW admin_stats AS
SELECT
  (SELECT COUNT(*) FROM auth.users) as total_users,
  (SELECT COUNT(*) FROM gmail_accounts) as connected_accounts,
  (SELECT COUNT(*) FROM sync_jobs WHERE status = 'running') as active_syncs,
  (SELECT COUNT(*) FROM sync_jobs WHERE status = 'completed' AND started_at > NOW() - INTERVAL '24 hours') as syncs_completed_today,
  (SELECT COUNT(*) FROM sync_jobs WHERE status = 'failed' AND started_at > NOW() - INTERVAL '24 hours') as syncs_failed_today,
  (SELECT COUNT(*) FROM documents WHERE processed_at > NOW() - INTERVAL '24 hours') as documents_processed_today,
  (SELECT COUNT(*) FROM documents WHERE status = 'pending') as total_pending_documents,
  (SELECT COUNT(*) FROM documents WHERE status = 'approved') as total_approved_documents,
  (SELECT COUNT(*) FROM documents WHERE status = 'rejected') as total_rejected_documents,
  (SELECT COUNT(DISTINCT user_id) FROM sync_jobs WHERE started_at > NOW() - INTERVAL '24 hours') as active_users_today,
  (SELECT COALESCE(SUM(documents_found), 0) FROM sync_jobs WHERE started_at > NOW() - INTERVAL '24 hours') as total_documents_found_today,
  (SELECT COALESCE(SUM(duplicates_skipped), 0) FROM sync_jobs WHERE started_at > NOW() - INTERVAL '24 hours') as total_duplicates_skipped_today;

-- Grant access to authenticated users (RLS will control who sees what via is_admin())
GRANT SELECT ON admin_stats TO authenticated;

-- =====================================================
-- SYNC_JOBS_ADMIN VIEW (for admin log viewing)
-- Shows sync jobs without sensitive user data
-- =====================================================

DROP VIEW IF EXISTS admin_sync_logs;

CREATE VIEW admin_sync_logs AS
SELECT
  sj.id,
  sj.user_id,
  p.email as user_email,
  sj.status,
  sj.sync_from_date,
  sj.sync_to_date,
  sj.emails_scanned,
  sj.documents_found,
  sj.duplicates_skipped,
  sj.started_at,
  sj.completed_at,
  sj.error_message,
  EXTRACT(EPOCH FROM (COALESCE(sj.completed_at, NOW()) - sj.started_at)) as duration_seconds
FROM sync_jobs sj
LEFT JOIN profiles p ON sj.user_id = p.id
ORDER BY sj.started_at DESC;

GRANT SELECT ON admin_sync_logs TO authenticated;

-- =====================================================
-- IMPORTANT: Documents, Gmail Accounts, User Settings
-- remain user-isolated (admins CANNOT see them)
-- =====================================================

-- No changes to documents, gmail_accounts, or user_settings policies
-- These remain strictly user-isolated for privacy

-- =====================================================
-- Add index for faster admin queries
-- =====================================================

CREATE INDEX IF NOT EXISTS idx_sync_jobs_started_at ON sync_jobs(started_at DESC);
CREATE INDEX IF NOT EXISTS idx_sync_jobs_status_started ON sync_jobs(status, started_at DESC);

-- Add comments
COMMENT ON FUNCTION is_admin() IS 'Returns true if current user has admin role';
COMMENT ON VIEW admin_stats IS 'Aggregate statistics for admin dashboard (no PII)';
COMMENT ON VIEW admin_sync_logs IS 'Sync job logs for admin monitoring (includes user email only)';

-- ==========================================================================
-- supabase/migrations/012_add_archive_synced_emails.sql
-- ==========================================================================

-- Migration 012: Add archive_synced_emails column to user_settings
-- This column controls whether synced emails should be archived (removed from inbox)

ALTER TABLE user_settings
ADD COLUMN IF NOT EXISTS archive_synced_emails BOOLEAN DEFAULT false;

-- Add comment
COMMENT ON COLUMN user_settings.archive_synced_emails IS 'Whether to archive (remove from inbox) emails after syncing';

-- ==========================================================================
-- supabase/migrations/013_supabase_cron_sync.sql
-- ==========================================================================

-- Migration 013: Move cron job to Supabase using pg_cron + pg_net
-- This replaces Vercel Cron for auto-sync functionality

-- Enable required extensions (if not already enabled)
CREATE EXTENSION IF NOT EXISTS pg_cron;
CREATE EXTENSION IF NOT EXISTS pg_net;

-- Create a table to store cron configuration
CREATE TABLE IF NOT EXISTS cron_config (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  key TEXT UNIQUE NOT NULL,
  value TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert the app URL and cron secret (these need to be updated with actual values)
-- You'll need to update these after running the migration
INSERT INTO cron_config (key, value) VALUES
  ('app_url', 'https://your-app-url.vercel.app'),
  ('cron_secret', 'your-cron-secret-here')
ON CONFLICT (key) DO NOTHING;

-- Create a function to trigger the sync API
CREATE OR REPLACE FUNCTION trigger_auto_sync()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  app_url TEXT;
  cron_secret TEXT;
  request_id BIGINT;
BEGIN
  -- Get configuration
  SELECT value INTO app_url FROM cron_config WHERE key = 'app_url';
  SELECT value INTO cron_secret FROM cron_config WHERE key = 'cron_secret';

  -- Check if configuration exists
  IF app_url IS NULL OR cron_secret IS NULL THEN
    RAISE NOTICE 'Cron config not set. Please update cron_config table with app_url and cron_secret.';
    RETURN;
  END IF;

  -- Make HTTP request to the sync API
  SELECT net.http_post(
    url := app_url || '/api/cron/sync',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'Authorization', 'Bearer ' || cron_secret
    ),
    body := '{}'::jsonb
  ) INTO request_id;

  RAISE NOTICE 'Auto-sync triggered, request_id: %', request_id;
END;
$$;

-- Schedule the cron job to run every 15 minutes
-- Note: pg_cron uses UTC timezone
SELECT cron.schedule(
  'auto-sync-invoices',           -- job name
  '*/15 * * * *',                 -- every 15 minutes
  $$SELECT trigger_auto_sync()$$  -- function to call
);

-- Create a helper function to manually trigger sync (useful for testing)
CREATE OR REPLACE FUNCTION manual_trigger_sync()
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  PERFORM trigger_auto_sync();
  RETURN 'Sync triggered. Check sync_jobs table for results.';
END;
$$;

-- Create a view to see cron job status
CREATE OR REPLACE VIEW cron_job_status AS
SELECT
  jobid,
  jobname,
  schedule,
  command,
  nodename,
  nodeport,
  database,
  username,
  active
FROM cron.job
WHERE jobname = 'auto-sync-invoices';

-- Create a view to see recent cron runs
CREATE OR REPLACE VIEW cron_job_runs AS
SELECT
  runid,
  jobid,
  job_pid,
  database,
  username,
  command,
  status,
  return_message,
  start_time,
  end_time
FROM cron.job_run_details
ORDER BY start_time DESC
LIMIT 50;

-- Grant access to the views for authenticated users (admins can check status)
GRANT SELECT ON cron_job_status TO authenticated;
GRANT SELECT ON cron_job_runs TO authenticated;

-- Add RLS to cron_config (only service role can modify)
ALTER TABLE cron_config ENABLE ROW LEVEL SECURITY;

-- No policies = only service role can access
-- This is intentional for security

-- Add comment explaining how to update config
COMMENT ON TABLE cron_config IS 'Configuration for cron jobs. Update app_url and cron_secret via SQL Editor or service role.';

-- ==========================================================================
-- supabase/migrations/013b_update_cron_config.sql
-- ==========================================================================

-- Run this AFTER 013_supabase_cron_sync.sql to set your actual values
-- Replace the placeholder values with your actual configuration

-- Update with your actual app URL
UPDATE cron_config
SET value = 'https://your-actual-app-url.vercel.app', updated_at = NOW()
WHERE key = 'app_url';

-- Update with your actual CRON_SECRET (same value as in your .env.local)
UPDATE cron_config
SET value = 'your-actual-cron-secret', updated_at = NOW()
WHERE key = 'cron_secret';

-- Verify the configuration
SELECT * FROM cron_config;

-- Test the sync manually (optional)
-- SELECT manual_trigger_sync();

-- ==========================================================================
-- supabase/migrations/014_add_onboarding.sql
-- ==========================================================================

-- Migration 014: Add Onboarding Support
-- Adds fields to track user onboarding progress and demo invoices

-- Add onboarding fields to profiles table
ALTER TABLE profiles
ADD COLUMN IF NOT EXISTS onboarding_completed BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS onboarding_step INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS demo_invoice_created BOOLEAN DEFAULT false;

-- Add is_demo field to documents table
ALTER TABLE documents
ADD COLUMN IF NOT EXISTS is_demo BOOLEAN DEFAULT false;

-- Update the handle_new_user function to initialize onboarding fields
CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, avatar_url, onboarding_completed, onboarding_step, demo_invoice_created)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.raw_user_meta_data->>'name'),
    NEW.raw_user_meta_data->>'avatar_url',
    false,
    0,
    false
  )
  ON CONFLICT (id) DO UPDATE SET
    email = EXCLUDED.email,
    full_name = COALESCE(EXCLUDED.full_name, profiles.full_name),
    avatar_url = COALESCE(EXCLUDED.avatar_url, profiles.avatar_url),
    updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Add comments
COMMENT ON COLUMN profiles.onboarding_completed IS 'Whether user has completed the onboarding wizard';
COMMENT ON COLUMN profiles.onboarding_step IS 'Current step in onboarding wizard (0-4)';
COMMENT ON COLUMN profiles.demo_invoice_created IS 'Whether demo invoice has been created for this user';
COMMENT ON COLUMN documents.is_demo IS 'Whether this is a demo invoice for onboarding';

-- Create index for demo invoices
CREATE INDEX IF NOT EXISTS idx_documents_is_demo ON documents(user_id, is_demo) WHERE is_demo = true;

-- ==========================================================================
-- supabase/migrations/015_add_inbox_folder.sql
-- ==========================================================================

-- Migration: Add Inbox Folder Sync Feature
-- Description: Add support for syncing documents from a Google Drive inbox folder
-- Date: 2026-02-02

-- Add inbox folder configuration to user_settings
ALTER TABLE user_settings 
ADD COLUMN inbox_folder_id TEXT,
ADD COLUMN inbox_folder_name TEXT,
ADD COLUMN inbox_folder_enabled BOOLEAN DEFAULT false,
ADD COLUMN last_inbox_sync_at TIMESTAMPTZ,
ADD COLUMN pending_folder_id TEXT,
ADD COLUMN approved_folder_id TEXT;

-- Add source tracking to documents
ALTER TABLE documents 
ADD COLUMN source TEXT DEFAULT 'gmail' CHECK (source IN ('gmail', 'inbox_folder')),
ADD COLUMN inbox_file_id TEXT; -- Track original inbox file for cleanup

-- Create index for faster source filtering
CREATE INDEX IF NOT EXISTS idx_documents_source ON documents(user_id, source, status);

-- Add comments for documentation
COMMENT ON COLUMN documents.source IS 'Source of the document: gmail (from email) or inbox_folder (from Drive folder)';
COMMENT ON COLUMN documents.inbox_file_id IS 'Original Drive file ID from inbox folder (for cleanup after approval/rejection)';

-- ==========================================================================
-- supabase/migrations/20240204_multisource_schema.sql
-- ==========================================================================

-- Migration: Multi-source and Multi-attachment Support

-- 1. Update documents table to support multiple attachments per email
-- First, drop the existing constraint if it exists
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'documents_user_id_email_message_id_key') THEN
        ALTER TABLE documents DROP CONSTRAINT documents_user_id_email_message_id_key;
    END IF;
END $$;

-- Add new constraint including file_hash to allow multiple files per email
-- Using a unique index/constraint on user_id + email_message_id + file_hash
ALTER TABLE documents
ADD CONSTRAINT documents_user_id_email_message_id_file_hash_key 
UNIQUE (user_id, email_message_id, file_hash);

-- Start Change: Make gmail_account_id nullable for other sources (forwarding, upload)
ALTER TABLE documents ALTER COLUMN gmail_account_id DROP NOT NULL;
-- End Change

-- 2. Update user_settings table for new features
ALTER TABLE user_settings
ADD COLUMN IF NOT EXISTS inbound_email TEXT UNIQUE,
ADD COLUMN IF NOT EXISTS enabled_sources TEXT[] DEFAULT '{upload}'::TEXT[],
ADD COLUMN IF NOT EXISTS onboarding_completed BOOLEAN DEFAULT false;

-- Add index for inbound email lookup
CREATE INDEX IF NOT EXISTS idx_user_settings_inbound_email ON user_settings(inbound_email);

-- Comment on columns
COMMENT ON COLUMN user_settings.inbound_email IS 'Unique inbound email address for forwarding (e.g., slug@entuaava.resend.app)';
COMMENT ON COLUMN user_settings.enabled_sources IS 'List of enabled ingestion sources (gmail, forwarding, upload)';

-- ==========================================================================
-- database/app-auth.sql
-- ==========================================================================

create table if not exists public.app_credentials (
  profile_id uuid primary key references public.profiles(id) on delete cascade,
  password_hash text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists app_credentials_profile_id_idx
  on public.app_credentials (profile_id);

-- ==========================================================================
-- database/approved-filename-template.sql
-- ==========================================================================

alter table public.user_settings
add column if not exists approved_filename_template text;

comment on column public.user_settings.approved_filename_template is
  'Filename template applied when a document is approved. Supports {supplier_name}, {vat_number}, {month}, {year}, {invoice_number}, {invoice_total}, {currency}. NULL means use the built-in default.';

-- ==========================================================================
-- database/inbox-folder-mode.sql
-- ==========================================================================

alter table public.user_settings
add column if not exists inbox_folder_mode text
check (inbox_folder_mode in ('managed', 'existing'));

update public.user_settings
set inbox_folder_mode = case
  when inbox_folder_enabled = true and inbox_folder_name is not null and inbox_folder_name <> 'Inbox' then 'existing'
  else 'managed'
end
where inbox_folder_mode is null;

-- ==========================================================================
-- supabase/migrations/016_enable_rls_app_credentials.sql
-- ==========================================================================

-- Enable Row-Level Security on app_credentials table
-- This table stores password hashes and should only be accessible via service_role
ALTER TABLE public.app_credentials ENABLE ROW LEVEL SECURITY;

-- Add approved folder configuration columns to user_settings
ALTER TABLE user_settings
ADD COLUMN IF NOT EXISTS approved_folder_name TEXT,
ADD COLUMN IF NOT EXISTS approved_folder_mode TEXT DEFAULT 'managed' CHECK (approved_folder_mode IN ('managed', 'existing'));

-- ==========================================================================
-- supabase/migrations/017_add_auto_decision.sql
-- ==========================================================================

-- Auto-decision (learning) feature
--
-- Adds columns that let the ingestion pipeline act on a document automatically
-- based on prior user feedback (same file hash, sender reputation) instead of
-- always leaving it as 'pending'.
--
-- Design notes:
--   * We reuse status='rejected' / status='approved' instead of introducing new
--     statuses — the documents list query already filters by pending and this
--     keeps existing approved/rejected surfaces working unchanged.
--   * auto_action_reason is the audit trail. When NULL, the status change came
--     from a real user action; when set, it was an automatic decision that the
--     user can undo.
--   * The existing update_sender_reputation() trigger fires on user_feedback
--     insert — auto-decisions deliberately skip user_feedback so they don't
--     snowball the counters and lock a sender in forever after one rejection.

ALTER TABLE documents
  ADD COLUMN IF NOT EXISTS auto_action_reason TEXT;

COMMENT ON COLUMN documents.auto_action_reason IS
  'When set, the status was chosen automatically by the learning pipeline. Describes which rule fired (e.g. "file_hash_rejected", "sender_blocked"). NULL for user-initiated actions.';

-- User-level toggles for the auto-decision pipeline.
--   auto_reject_enabled defaults to true — it only triggers on strong signals
--     (exact file hash or blocked sender) so it is safe to opt users in.
--   auto_approve_enabled defaults to false — auto-approving moves files into
--     the user's Approved/MM-YYYY folder and records them as finished, which is
--     harder to undo and should be explicitly opted into.
ALTER TABLE user_settings
  ADD COLUMN IF NOT EXISTS auto_reject_enabled BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE user_settings
  ADD COLUMN IF NOT EXISTS auto_approve_enabled BOOLEAN NOT NULL DEFAULT false;

-- Index to make the "has this file_hash been rejected before?" lookup cheap.
-- Partial index keeps it small — we only care about rejected rows.
CREATE INDEX IF NOT EXISTS idx_documents_user_hash_rejected
  ON documents (user_id, file_hash)
  WHERE status = 'rejected';

-- ==========================================================================
-- supabase/migrations/018_rename_drive_upload_sender.sql
-- ==========================================================================

-- Backfill: rename legacy "Drive Upload" sender label to "Inbox folder".
--
-- The inbox-folder ingestion path historically labelled the synthetic sender as
-- "Drive Upload", which made pending documents appear as if they'd been
-- manually uploaded via an invoice portal. The source is actually the user's
-- linked Google Drive inbox folder.
UPDATE documents
SET sender = 'Inbox folder'
WHERE sender = 'Drive Upload';

-- ==========================================================================
-- supabase/migrations/019_multi_user_accounts.sql
-- ==========================================================================

-- Migration 019: Multi-user accounts (invite-only signup + password reset)
--
-- Turns the single-user app into a shared one. Three concerns:
--
--   1. Stop new users inheriting the app owner's infrastructure.
--   2. Give accounts a lifecycle (invited / active / suspended) and a paper
--      trail of who let each person in.
--   3. Back the two credential flows that had no storage: invite codes and
--      password resets.
--
-- Identity note: profiles.id, user_settings.user_id, documents.user_id and
-- gmail_accounts.user_id all reference auth.users(id). Rather than tear out
-- six foreign keys, account creation goes through auth.admin.createUser() and
-- the existing handle_new_user() trigger populates profiles. Supabase Auth
-- stays the identity store; app_credentials + the signed session cookie remain
-- the login mechanism.

-- ---------------------------------------------------------------------------
-- 1. No shared classifier by default
-- ---------------------------------------------------------------------------

-- This column defaulted to the app owner's n8n endpoint, so every new account
-- would classify documents through the owner's instance — their quota, their
-- bill, their logs — without anyone choosing that. New users now start with no
-- classifier until they configure one.
ALTER TABLE user_settings
  ALTER COLUMN webhook_url DROP DEFAULT;

COMMENT ON COLUMN user_settings.webhook_url IS
  'Per-user classification endpoint. NULL means no classifier is configured; documents are stored unclassified rather than falling back to a shared endpoint.';

-- ---------------------------------------------------------------------------
-- 2. Account lifecycle
-- ---------------------------------------------------------------------------

DO $$ BEGIN
  CREATE TYPE profile_status AS ENUM ('invited', 'active', 'suspended');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS status profile_status NOT NULL DEFAULT 'active',
  ADD COLUMN IF NOT EXISTS invited_by UUID REFERENCES profiles(id) ON DELETE SET NULL;

COMMENT ON COLUMN profiles.status IS
  'active = may log in. suspended = credentials valid but access refused. invited = placeholder for a redeemed-but-not-yet-completed signup.';
COMMENT ON COLUMN profiles.invited_by IS
  'Admin whose invite code created this account. NULL for the original owner.';

-- Existing accounts predate invites and are active by definition.
UPDATE profiles SET status = 'active' WHERE status IS NULL;

-- ---------------------------------------------------------------------------
-- 3. Invite codes
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS invite_codes (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  -- Stored in plaintext deliberately: an admin needs to re-read a code to
  -- resend it, and the code is single-use, expiring, and worth only one
  -- account. Password reset tokens below are hashed, because those are
  -- credential-equivalent.
  code TEXT NOT NULL UNIQUE,
  -- Optional: when set, only this address may redeem the code.
  email TEXT,
  created_by UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  used_by UUID REFERENCES profiles(id) ON DELETE SET NULL,
  used_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ NOT NULL,
  revoked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS invite_codes_code_idx ON invite_codes (code);
CREATE INDEX IF NOT EXISTS invite_codes_created_by_idx ON invite_codes (created_by);

COMMENT ON TABLE invite_codes IS
  'Single-use signup codes. Redeemable while used_at IS NULL, revoked_at IS NULL and expires_at is in the future.';

-- ---------------------------------------------------------------------------
-- 4. Password reset tokens
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS password_reset_tokens (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  profile_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  -- SHA-256 of the token. The plaintext exists only in the email we send, so a
  -- database read cannot be turned into an account takeover.
  token_hash TEXT NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ NOT NULL,
  used_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS password_reset_tokens_hash_idx ON password_reset_tokens (token_hash);
CREATE INDEX IF NOT EXISTS password_reset_tokens_profile_idx ON password_reset_tokens (profile_id);

COMMENT ON TABLE password_reset_tokens IS
  'Single-use password reset tokens. Only the SHA-256 hash is stored.';

-- ---------------------------------------------------------------------------
-- 5. RLS
-- ---------------------------------------------------------------------------

-- Both tables are credential infrastructure and are only ever touched by
-- server-side service-role code. Enabling RLS with no policies denies all
-- access to the anon and authenticated roles, which is exactly what we want —
-- the same posture as app_credentials (migration 016).
ALTER TABLE invite_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE password_reset_tokens ENABLE ROW LEVEL SECURITY;

-- ==========================================================================
-- supabase/migrations/020_classification_metadata.sql
-- ==========================================================================

-- Migration 020: Classification metadata
--
-- Classification today is a single opaque `document_type` string from the n8n
-- webhook. When it is wrong — and at roughly a 70-80% hit rate it often is —
-- there is nothing recorded to explain why, no confidence to threshold on, and
-- nothing to tune. Non-invoices get accepted as invoices, and the Drive file of
-- anything judged "not an invoice" is deleted with no record that it existed.
--
-- These columns make a classification decision inspectable and gateable:
--
--   confidence_score      already existed, but was written as a meaningless
--                         1.0 / 0.5 flag for "webhook answered / didn't". It
--                         now carries a real 0..1 confidence.
--   classification_source which layer decided (prefilter / webhook / llm / none)
--   classification_reason human-readable justification, shown in the UI
--   needs_review          the decision was not confident enough to trust; the
--                         document stays pending and is flagged for the user
--   prefilter_matched     which deterministic rules fired, for debugging

ALTER TABLE documents
  ADD COLUMN IF NOT EXISTS classification_source TEXT,
  ADD COLUMN IF NOT EXISTS classification_reason TEXT,
  ADD COLUMN IF NOT EXISTS needs_review BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS prefilter_matched JSONB;

COMMENT ON COLUMN documents.classification_source IS
  'Which layer produced the classification: prefilter | webhook | llm | none.';
COMMENT ON COLUMN documents.classification_reason IS
  'Human-readable explanation of the classification, surfaced in the UI so a wrong call can be understood rather than just corrected.';
COMMENT ON COLUMN documents.needs_review IS
  'Set when confidence fell below the trust threshold. The document stays pending; the UI flags it instead of silently presenting a low-confidence guess as fact.';
COMMENT ON COLUMN documents.prefilter_matched IS
  'Deterministic rules that fired during pre-filtering, e.g. {"negative":["statement"],"positive":[]}.';
COMMENT ON COLUMN documents.confidence_score IS
  'Classifier confidence, 0..1. Previously a 1.0/0.5 flag meaning "webhook responded"; now a real score.';

-- Pending documents needing attention is the query the dashboard runs most.
CREATE INDEX IF NOT EXISTS idx_documents_user_needs_review
  ON documents (user_id, needs_review)
  WHERE status = 'pending';

-- ---------------------------------------------------------------------------
-- Per-user classification tuning
-- ---------------------------------------------------------------------------

-- Below this, a classification is flagged for review rather than trusted.
-- Default 0.7: the webhook currently reports no confidence at all, so its
-- results are assigned a fixed score and this threshold only bites once a real
-- confidence signal exists (Phase 4b). Exposed per user because tolerance for
-- false positives vs manual review differs by workflow.
ALTER TABLE user_settings
  ADD COLUMN IF NOT EXISTS classification_confidence_threshold NUMERIC(3,2)
    NOT NULL DEFAULT 0.70
    CHECK (classification_confidence_threshold >= 0 AND classification_confidence_threshold <= 1);

-- The deterministic pre-filter runs before Drive upload and before the
-- classifier, so obvious non-invoices cost nothing. Opt-out exists because a
-- filename-based heuristic can in principle skip something wanted, and the
-- user should be able to turn it off without a code change.
ALTER TABLE user_settings
  ADD COLUMN IF NOT EXISTS prefilter_enabled BOOLEAN NOT NULL DEFAULT true;

COMMENT ON COLUMN user_settings.classification_confidence_threshold IS
  'Classifications scoring below this are marked needs_review instead of being accepted outright.';
COMMENT ON COLUMN user_settings.prefilter_enabled IS
  'Run the deterministic filename/subject pre-filter before uploading and classifying.';

-- ==========================================================================
-- supabase/migrations/021_sibling_documents.sql
-- ==========================================================================

-- Migration 021: Sibling documents (invoice + receipt pairs)
--
-- Senders like Stripe attach both an invoice and a receipt to the same email.
-- They describe one transaction, and Portuguese bookkeeping generally needs only
-- one of them — but the pipeline treated them as two unrelated files. Worse,
-- before migration 020 the receipt was usually deleted outright, because
-- anything the classifier did not call `supplier_invoice` had its Drive file
-- removed and no row written.
--
-- Grouping key: no new column. Documents already carry (user_id,
-- email_message_id), which is exactly "the attachments of one email" — the
-- unique constraint on (user_id, email_message_id, file_hash) is built on it.
-- Drive-inbox files use a per-file synthetic id, so each is its own group,
-- which is correct: unrelated uploads must never be paired.

-- ---------------------------------------------------------------------------
-- 1. Document variant
-- ---------------------------------------------------------------------------

-- final_classification collapses everything that is not an invoice or credit
-- note into 'unclassified', which loses the invoice-vs-receipt distinction that
-- pairing depends on.
ALTER TABLE documents
  ADD COLUMN IF NOT EXISTS variant TEXT;

COMMENT ON COLUMN documents.variant IS
  'Finer-grained document kind from the classifier: invoice | receipt | credit_note | other. Distinct from final_classification, which collapses receipts into unclassified.';

-- ---------------------------------------------------------------------------
-- 2. Pair state
-- ---------------------------------------------------------------------------

DO $$ BEGIN
  CREATE TYPE document_pair_state AS ENUM (
    'unpaired',           -- no sibling detected; the normal case
    'awaiting_choice',    -- a pair was found and the user must pick
    'kept',               -- chosen (or auto-chosen) side of a pair
    'discarded_duplicate' -- the other side, dropped as a duplicate of `kept`
  );
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

ALTER TABLE documents
  ADD COLUMN IF NOT EXISTS pair_state document_pair_state NOT NULL DEFAULT 'unpaired',
  ADD COLUMN IF NOT EXISTS paired_with_id UUID REFERENCES documents(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS pair_reason TEXT;

COMMENT ON COLUMN documents.pair_state IS
  'Lifecycle of this document within an invoice/receipt pair.';
COMMENT ON COLUMN documents.paired_with_id IS
  'The sibling document describing the same transaction.';
COMMENT ON COLUMN documents.pair_reason IS
  'Why these two were considered the same transaction (matching total, shared filename stem, ...). Shown in the UI so an incorrect pairing is explicable.';

-- The pending list groups by email; this makes that grouping cheap.
CREATE INDEX IF NOT EXISTS idx_documents_user_message
  ON documents (user_id, email_message_id);

-- ---------------------------------------------------------------------------
-- 3. Per-user preference
-- ---------------------------------------------------------------------------

-- Defaults to 'invoice': in Portugal the invoice is the document that matters
-- for accounting, and defaulting to a real choice means the common case needs
-- no interaction at all. 'ask' is available for users who want to decide each
-- time.
ALTER TABLE user_settings
  ADD COLUMN IF NOT EXISTS duplicate_pair_default TEXT
    NOT NULL DEFAULT 'invoice'
    CHECK (duplicate_pair_default IN ('ask', 'invoice', 'receipt', 'both'));

COMMENT ON COLUMN user_settings.duplicate_pair_default IS
  'What to keep when one email contains both an invoice and a receipt for the same transaction: ask | invoice | receipt | both.';

-- ==========================================================================
-- supabase/migrations/022_user_api_keys.sql
-- ==========================================================================

-- Migration 022: Per-user LLM API keys
--
-- Each user brings their own provider key so classification runs on their
-- account and their bill, rather than everyone sharing the app owner's
-- infrastructure. This is the storage half; lib/crypto.ts does the encryption
-- and the classifier resolves which backend to use.
--
-- Security posture:
--   * encrypted_key holds AES-256-GCM ciphertext, never plaintext. The
--     encryption key lives in ENCRYPTION_KEY, outside the database, so a
--     database compromise alone does not yield usable provider credentials.
--   * key_hint is the only part ever returned to a client (`sk-ant-…4f2a`).
--   * RLS is enabled with no policies: service-role access only, same posture
--     as app_credentials and password_reset_tokens.

CREATE TABLE IF NOT EXISTS user_api_keys (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  provider TEXT NOT NULL CHECK (provider IN ('anthropic', 'openai')),
  encrypted_key TEXT NOT NULL,
  key_hint TEXT NOT NULL,
  -- Result of the validation call made when the key was saved.
  status TEXT NOT NULL DEFAULT 'unverified'
    CHECK (status IN ('unverified', 'valid', 'invalid')),
  last_validated_at TIMESTAMPTZ,
  last_error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- One key per provider per user. Saving again replaces the previous key
  -- rather than accumulating stale credentials.
  UNIQUE (user_id, provider)
);

CREATE INDEX IF NOT EXISTS user_api_keys_user_idx ON user_api_keys (user_id);

COMMENT ON TABLE user_api_keys IS
  'Per-user LLM provider credentials, encrypted at rest with AES-256-GCM.';
COMMENT ON COLUMN user_api_keys.encrypted_key IS
  'AES-256-GCM ciphertext in the form v1.<iv>.<tag>.<data>. Never return this to a client.';
COMMENT ON COLUMN user_api_keys.key_hint IS
  'Non-secret display fragment, e.g. sk-ant-...4f2a. Safe to send to the browser.';

ALTER TABLE user_api_keys ENABLE ROW LEVEL SECURITY;

DROP TRIGGER IF EXISTS update_user_api_keys_updated_at ON user_api_keys;
CREATE TRIGGER update_user_api_keys_updated_at
  BEFORE UPDATE ON user_api_keys
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ---------------------------------------------------------------------------
-- Which backend classifies this user's documents
-- ---------------------------------------------------------------------------

-- Resolution order is: the named provider's key -> the user's webhook_url ->
-- nothing (documents stored unclassified and flagged for review). Defaulting to
-- 'webhook' keeps every existing user on exactly the path they are on today;
-- adding a key does nothing until this is switched.
ALTER TABLE user_settings
  ADD COLUMN IF NOT EXISTS classifier_backend TEXT
    NOT NULL DEFAULT 'webhook'
    CHECK (classifier_backend IN ('webhook', 'anthropic', 'openai'));

COMMENT ON COLUMN user_settings.classifier_backend IS
  'Which classification backend to use. Falls back to webhook_url if the selected provider has no usable key.';

-- ==========================================================================
-- supabase/migrations/023_llm_classification.sql
-- ==========================================================================

-- Migration 023: LLM classification + usage tracking
--
-- Migration 022 stored per-user provider keys. This is what makes them do
-- something: the model to call, and a record of what each call cost.
--
-- Usage tracking is not optional bookkeeping here. Users are spending their own
-- money through their own key, on documents this app decided to send. Without a
-- per-document record of tokens spent there is no way for them to check the
-- bill against what actually happened, and no way to diagnose a
-- misclassification after the fact.

-- ---------------------------------------------------------------------------
-- 1. Model selection
-- ---------------------------------------------------------------------------

-- Nullable: NULL means "use the provider default from lib/classifier/providers".
-- Exposed because model availability changes faster than this codebase does —
-- a user whose account lacks the default model, or who wants a cheaper or
-- stronger one, must be able to fix that without a deploy.
ALTER TABLE user_settings
  ADD COLUMN IF NOT EXISTS classifier_model TEXT;

COMMENT ON COLUMN user_settings.classifier_model IS
  'Model id to use for classification. NULL uses the provider default. Set this if the default model is unavailable on your account.';

-- ---------------------------------------------------------------------------
-- 2. Usage log
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS llm_usage (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  -- Nullable: a call can fail before any document row exists, and we still want
  -- the spend recorded.
  document_id UUID REFERENCES documents(id) ON DELETE SET NULL,
  provider TEXT NOT NULL,
  model TEXT NOT NULL,
  input_tokens INTEGER NOT NULL DEFAULT 0,
  output_tokens INTEGER NOT NULL DEFAULT 0,
  -- Whether the call produced a usable classification. Failed calls still cost
  -- money, so they belong in the same ledger.
  succeeded BOOLEAN NOT NULL DEFAULT true,
  error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS llm_usage_user_created_idx
  ON llm_usage (user_id, created_at DESC);

COMMENT ON TABLE llm_usage IS
  'Per-call record of LLM spend against a user''s own API key. Deliberately includes failed calls, which are billed too.';

ALTER TABLE llm_usage ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------------------------
-- 3. Record which model classified each document
-- ---------------------------------------------------------------------------

-- classification_source (migration 020) records the layer; this records the
-- specific model, so a drop in accuracy after a model change is attributable.
ALTER TABLE documents
  ADD COLUMN IF NOT EXISTS classification_model TEXT;

COMMENT ON COLUMN documents.classification_model IS
  'Model that produced the classification, e.g. claude-haiku-4-5-20251001. Null for webhook or prefilter decisions.';

-- ==========================================================================
-- supabase/migrations/024_classification_rules.sql
-- ==========================================================================

-- Migration 024: User-defined classification rules
--
-- The built-in pre-filter and prompt encode general knowledge about what an
-- invoice looks like. They cannot know that *this* user's accountant sends
-- monthly PDFs that are never invoices, or that a particular supplier's
-- statements should always be skipped. Rules are how a user teaches the
-- pipeline about their own mail without a code change.
--
-- Rules attach to one of the three pipeline layers:
--
--   pre_filter     runs before Drive upload and before any classifier call.
--                  Deterministic and free — the right place for "never process
--                  anything from this domain".
--   prompt_hint    injected into the classifier prompt as a natural-language
--                  instruction. For judgements a pattern cannot express.
--   post_decision  applied to the classifier's answer. Overrides or forces
--                  review.

DO $$ BEGIN
  CREATE TYPE classification_rule_stage AS ENUM ('pre_filter', 'prompt_hint', 'post_decision');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  CREATE TYPE classification_rule_match AS ENUM (
    'sender_domain',   -- exact domain match
    'sender_email',    -- exact address match
    'filename_regex',  -- user-supplied pattern, length- and time-guarded
    'subject_keyword', -- case-insensitive substring
    'nl_instruction'   -- free text, only meaningful for prompt_hint
  );
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  CREATE TYPE classification_rule_action AS ENUM (
    'skip',              -- discard without storing
    'force_invoice',     -- classify as invoice regardless
    'force_not_invoice', -- classify as other regardless
    'require_review',    -- keep, but always flag for the user
    'hint'               -- prompt_hint only: advice, not a verdict
  );
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

CREATE TABLE IF NOT EXISTS classification_rules (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT true,
  -- Lower runs first. Ties break on created_at so ordering is always total and
  -- a rule list cannot reorder itself between requests.
  priority INTEGER NOT NULL DEFAULT 100,
  stage classification_rule_stage NOT NULL,
  match_type classification_rule_match NOT NULL,
  -- The domain, address, pattern, keyword or instruction text.
  match_value TEXT NOT NULL,
  action classification_rule_action NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- Bounded so a pathological pattern cannot be stored in the first place;
  -- lib/classifier/rules.ts additionally guards evaluation time.
  CONSTRAINT classification_rules_value_length CHECK (char_length(match_value) BETWEEN 1 AND 500),
  CONSTRAINT classification_rules_name_length CHECK (char_length(name) BETWEEN 1 AND 100)
);

CREATE INDEX IF NOT EXISTS classification_rules_user_idx
  ON classification_rules (user_id, enabled, priority);

COMMENT ON TABLE classification_rules IS
  'Per-user rules layered onto the built-in classification pipeline.';
COMMENT ON COLUMN classification_rules.priority IS
  'Lower runs first. Ties break on created_at.';
COMMENT ON COLUMN classification_rules.match_value IS
  'Interpretation depends on match_type. For filename_regex this is user input and is evaluated under a length cap and time guard.';

ALTER TABLE classification_rules ENABLE ROW LEVEL SECURITY;

DROP TRIGGER IF EXISTS update_classification_rules_updated_at ON classification_rules;
CREATE TRIGGER update_classification_rules_updated_at
  BEFORE UPDATE ON classification_rules
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Which rules fired for a document, for explaining an outcome after the fact.
-- documents.prefilter_matched (migration 020) covers the built-in rules; this
-- covers the user's own.
ALTER TABLE documents
  ADD COLUMN IF NOT EXISTS rules_applied JSONB;

COMMENT ON COLUMN documents.rules_applied IS
  'User-defined rules that fired for this document, as [{id, name, action}]. Null when none applied.';

-- ==========================================================================
-- supabase/migrations/20260204_secure_cron_views.sql
-- ==========================================================================

-- Secure Cron Views
-- These views share system-wide cron logs and were previously accessible to all authenticated users.
-- This restricts access to only the service_role (backend/admin) to prevent information leakage.

REVOKE SELECT ON cron_job_runs FROM authenticated;
REVOKE SELECT ON cron_job_runs FROM anon;

REVOKE SELECT ON cron_job_status FROM authenticated;
REVOKE SELECT ON cron_job_status FROM anon;

-- Explicitly ensure service_role has access
GRANT SELECT ON cron_job_runs TO service_role;
GRANT SELECT ON cron_job_status TO service_role;

-- ==========================================================================
-- supabase/migrations/025_fix_admin_views.sql
-- ==========================================================================

-- Migration 025: Recreate the admin dashboard views
--
-- The /admin dashboard showed 0 for every metric against a database holding
-- 4 users, 168 documents and 8047 sync jobs. Cause: admin_stats and
-- admin_sync_logs did not exist. The page reads them with
-- `stats?.total_users || 0`, so a missing view is indistinguishable from a
-- genuinely empty system — it renders zeros instead of failing.
--
-- Recreated here, with three corrections to the original definitions.

DROP VIEW IF EXISTS admin_stats;
DROP VIEW IF EXISTS admin_sync_logs;

-- ---------------------------------------------------------------------------
-- admin_stats
-- ---------------------------------------------------------------------------

CREATE VIEW admin_stats AS
SELECT
  -- Correction 1: count profiles, not auth.users.
  --
  -- profiles is what this application manages; auth.users is the identity
  -- store underneath it. They should agree, but when they disagree the
  -- meaningful number is the one the app can actually act on. Suspended
  -- accounts are excluded because "Utilizadores" on the dashboard means people
  -- who can currently use the system.
  (SELECT COUNT(*) FROM profiles WHERE status <> 'suspended') AS total_users,

  (SELECT COUNT(*) FROM gmail_accounts) AS connected_accounts,
  (SELECT COUNT(*) FROM sync_jobs WHERE status = 'running') AS active_syncs,

  -- Correction 2: "today" means the calendar day, not a rolling 24 hours.
  --
  -- The dashboard labels these "Hoje". A rolling window makes the number drift
  -- during the day and disagree with anything the user counts by hand.
  (SELECT COUNT(*) FROM sync_jobs
    WHERE status = 'completed' AND started_at >= date_trunc('day', NOW())) AS syncs_completed_today,
  (SELECT COUNT(*) FROM sync_jobs
    WHERE status = 'failed' AND started_at >= date_trunc('day', NOW())) AS syncs_failed_today,
  (SELECT COUNT(*) FROM documents
    WHERE processed_at >= date_trunc('day', NOW())) AS documents_processed_today,

  (SELECT COUNT(*) FROM documents WHERE status = 'pending') AS total_pending_documents,
  (SELECT COUNT(*) FROM documents WHERE status = 'approved') AS total_approved_documents,
  (SELECT COUNT(*) FROM documents WHERE status = 'rejected') AS total_rejected_documents,

  (SELECT COUNT(DISTINCT user_id) FROM sync_jobs
    WHERE started_at >= date_trunc('day', NOW())) AS active_users_today,
  (SELECT COALESCE(SUM(documents_found), 0) FROM sync_jobs
    WHERE started_at >= date_trunc('day', NOW())) AS total_documents_found_today,
  (SELECT COALESCE(SUM(duplicates_skipped), 0) FROM sync_jobs
    WHERE started_at >= date_trunc('day', NOW())) AS total_duplicates_skipped_today;

-- ---------------------------------------------------------------------------
-- admin_sync_logs
-- ---------------------------------------------------------------------------

CREATE VIEW admin_sync_logs AS
SELECT
  sj.id,
  sj.user_id,
  p.email AS user_email,
  sj.status,
  sj.sync_from_date,
  sj.sync_to_date,
  sj.emails_scanned,
  sj.documents_found,
  sj.duplicates_skipped,
  sj.started_at,
  sj.completed_at,
  sj.error_message,
  EXTRACT(EPOCH FROM (sj.completed_at - sj.started_at))::INTEGER AS duration_seconds
FROM sync_jobs sj
LEFT JOIN profiles p ON p.id = sj.user_id
ORDER BY sj.started_at DESC;

-- ---------------------------------------------------------------------------
-- Access
-- ---------------------------------------------------------------------------

-- Correction 3: do not grant these to `authenticated`.
--
-- The original granted SELECT to authenticated on the assumption that RLS
-- would filter by role. It does not: these are views over aggregates, RLS on
-- the underlying tables is bypassed by the view's owner privileges, and there
-- is no policy on a view to enforce is_admin(). Any logged-in user could read
-- system-wide counts and every user's sync history including their email.
--
-- The application reads these with the service role and separately checks that
-- the caller is an admin (middleware, the /admin layout, and the page itself),
-- so service_role is the only grant needed.
REVOKE ALL ON admin_stats FROM authenticated, anon;
REVOKE ALL ON admin_sync_logs FROM authenticated, anon;

GRANT SELECT ON admin_stats TO service_role;
GRANT SELECT ON admin_sync_logs TO service_role;

COMMENT ON VIEW admin_stats IS
  'Aggregate statistics for the admin dashboard. service_role only — the application enforces the admin role check.';
COMMENT ON VIEW admin_sync_logs IS
  'Recent sync jobs with the owning user''s email. service_role only — contains PII.';

-- ==========================================================================
-- supabase/migrations/026_revoke_cron_rpc.sql
-- ==========================================================================

-- trigger_auto_sync() and manual_trigger_sync() are SECURITY DEFINER and, by
-- Postgres default, executable by PUBLIC. That exposed them through PostgREST
-- (POST /rest/v1/rpc/manual_trigger_sync) to anyone holding the public anon
-- key, letting them fire the cron sweep on demand. Only pg_cron (running as
-- the owner) needs to call them.

REVOKE EXECUTE ON FUNCTION trigger_auto_sync() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION manual_trigger_sync() FROM PUBLIC, anon, authenticated;

-- Pin search_path so a SECURITY DEFINER body can't be hijacked by objects in
-- a caller-controlled schema.
ALTER FUNCTION trigger_auto_sync() SET search_path = public, extensions, net;
ALTER FUNCTION manual_trigger_sync() SET search_path = public, extensions, net;

-- ==========================================================================
-- supabase/migrations/027_document_notified_at.sql
-- ==========================================================================

-- Durable "new documents" notifications.
--
-- The email used to be built from an in-memory list at the end of a sync. If
-- the function died after documents were committed (timeout, crash) or Resend
-- rejected the send, those documents were never notified: the next run saw
-- them as duplicates. Notification state now lives on the row, so anything
-- not yet notified is picked up by the next run.

ALTER TABLE documents ADD COLUMN IF NOT EXISTS notified_at TIMESTAMPTZ;

-- Existing rows were either already notified or are too old to be news;
-- mark them so the first run after deploy doesn't email the whole backlog.
UPDATE documents SET notified_at = COALESCE(created_at, NOW()) WHERE notified_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_documents_unnotified
  ON documents (user_id, created_at)
  WHERE notified_at IS NULL;

-- pg_net gives up on a request after 5s by default. The sync sweep runs far
-- longer (maxDuration = 300 on /api/cron/sync), so match it; otherwise the
-- request is abandoned and failures never show up in net._http_response.
-- CREATE OR REPLACE resets function settings, so search_path from 026 is
-- restated here.
CREATE OR REPLACE FUNCTION trigger_auto_sync()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions, net
AS $$
DECLARE
  app_url TEXT;
  cron_secret TEXT;
  request_id BIGINT;
BEGIN
  SELECT value INTO app_url FROM cron_config WHERE key = 'app_url';
  SELECT value INTO cron_secret FROM cron_config WHERE key = 'cron_secret';

  IF app_url IS NULL OR cron_secret IS NULL THEN
    RAISE NOTICE 'Cron config not set. Please update cron_config table with app_url and cron_secret.';
    RETURN;
  END IF;

  SELECT net.http_post(
    url := app_url || '/api/cron/sync',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'Authorization', 'Bearer ' || cron_secret
    ),
    body := '{}'::jsonb,
    timeout_milliseconds := 300000
  ) INTO request_id;

  RAISE NOTICE 'Auto-sync triggered, request_id: %', request_id;
END;
$$;

REVOKE EXECUTE ON FUNCTION trigger_auto_sync() FROM PUBLIC, anon, authenticated;

-- ==========================================================================
-- supabase/migrations/028_lock_signup_and_session_version.sql
-- ==========================================================================

-- Migration 028: Close the self-signup bypass and make sessions revocable
--
-- 1. handle_new_user() created an *active* profile for every auth.users row
--    (profiles.status defaults to 'active' since 019). Anyone holding the
--    public anon key could call supabase.auth.signUp(), get an active profile,
--    then use forgot-password/reset-password to mint app credentials — a full
--    account with no invite. New rows now start as 'invited'; the invite-only
--    signup route (app/api/auth/signup) promotes its own users to 'active'
--    explicitly once the invite is validated.
--
-- 2. Session cookies are stateless HMAC tokens valid for 30 days, so
--    suspending a user or resetting a leaked password left existing sessions
--    working. profiles.session_version is embedded in the token and compared
--    on every request; bumping it invalidates every outstanding session.

-- ---------------------------------------------------------------------------
-- 1. Self-signup no longer yields an active profile
-- ---------------------------------------------------------------------------

-- Belt and braces: even a code path that inserts a profile without naming the
-- status now gets the inert state.
ALTER TABLE profiles ALTER COLUMN status SET DEFAULT 'invited';

CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, avatar_url, onboarding_completed, onboarding_step, demo_invoice_created, status)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.raw_user_meta_data->>'name'),
    NEW.raw_user_meta_data->>'avatar_url',
    false,
    0,
    false,
    'invited'
  )
  -- status deliberately not touched on conflict: re-creating an auth user
  -- must not demote (or promote) an existing account.
  ON CONFLICT (id) DO UPDATE SET
    email = EXCLUDED.email,
    full_name = COALESCE(EXCLUDED.full_name, profiles.full_name),
    avatar_url = COALESCE(EXCLUDED.avatar_url, profiles.avatar_url),
    updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- ---------------------------------------------------------------------------
-- 2. Revocable sessions
-- ---------------------------------------------------------------------------

ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS session_version INTEGER NOT NULL DEFAULT 0;

COMMENT ON COLUMN profiles.session_version IS
  'Embedded in the signed session cookie. Incrementing it logs the user out everywhere. Bumped automatically on status change and password change.';

-- Bumped in the database rather than in each route, so a suspension or
-- password change made from the Supabase SQL editor / dashboard revokes
-- sessions just as reliably as one made through the app.

CREATE OR REPLACE FUNCTION bump_session_version_on_status_change()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.status IS DISTINCT FROM OLD.status THEN
    NEW.session_version := OLD.session_version + 1;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SET search_path = public;

DROP TRIGGER IF EXISTS profiles_bump_session_version ON profiles;
CREATE TRIGGER profiles_bump_session_version
  BEFORE UPDATE OF status ON profiles
  FOR EACH ROW
  EXECUTE FUNCTION bump_session_version_on_status_change();

CREATE OR REPLACE FUNCTION bump_session_version_on_password_change()
RETURNS TRIGGER AS $$
BEGIN
  -- Inserts count too: reset-password upserts, and the first credential row
  -- for an account should not honour any session issued before it existed.
  IF TG_OP = 'INSERT' OR NEW.password_hash IS DISTINCT FROM OLD.password_hash THEN
    UPDATE public.profiles
      SET session_version = session_version + 1
      WHERE id = NEW.profile_id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

DROP TRIGGER IF EXISTS app_credentials_bump_session_version ON app_credentials;
CREATE TRIGGER app_credentials_bump_session_version
  AFTER INSERT OR UPDATE OF password_hash ON app_credentials
  FOR EACH ROW
  EXECUTE FUNCTION bump_session_version_on_password_change();

-- ==========================================================================
-- supabase/migrations/029_auth_rate_limits.sql
-- ==========================================================================

-- Migration 029: Rate limiting for the public auth endpoints
--
-- login, signup, forgot-password and reset-password are unauthenticated.
-- Without a limit they allow online password guessing and reset-email
-- flooding. The app runs on Vercel serverless, so an in-memory counter would
-- reset on every cold start and is not shared between instances; the counter
-- lives here instead.
--
-- Fixed-window counters keyed by an opaque string chosen by lib/rate-limit.ts
-- (e.g. 'login:ip:1.2.3.4'). Only the service role touches this table.

CREATE TABLE IF NOT EXISTS auth_rate_limits (
  key TEXT NOT NULL,
  window_start TIMESTAMPTZ NOT NULL,
  count INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (key, window_start)
);

-- For pruning old windows.
CREATE INDEX IF NOT EXISTS auth_rate_limits_window_start_idx
  ON auth_rate_limits (window_start);

-- RLS on with no policies: anon/authenticated get nothing through PostgREST.
-- The service role bypasses RLS.
ALTER TABLE auth_rate_limits ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE auth_rate_limits IS
  'Fixed-window request counters for unauthenticated auth endpoints. Written only via hit_rate_limit().';

-- Records one hit against p_key and reports whether the caller is now over
-- p_max for the current p_window_seconds window. The increment is a single
-- upsert, so concurrent requests cannot both read a stale count and slip
-- under the limit.
CREATE OR REPLACE FUNCTION hit_rate_limit(p_key TEXT, p_window_seconds INTEGER, p_max INTEGER)
RETURNS BOOLEAN AS $$
DECLARE
  v_window TIMESTAMPTZ;
  v_count INTEGER;
BEGIN
  v_window := to_timestamp(
    floor(extract(epoch FROM now()) / p_window_seconds) * p_window_seconds
  );

  INSERT INTO auth_rate_limits AS r (key, window_start, count)
  VALUES (p_key, v_window, 1)
  ON CONFLICT (key, window_start)
  DO UPDATE SET count = r.count + 1
  RETURNING r.count INTO v_count;

  -- Opportunistic cleanup so the table does not grow without bound. Cheap
  -- thanks to the window_start index; a day comfortably exceeds every window
  -- the app uses.
  IF random() < 0.01 THEN
    DELETE FROM auth_rate_limits WHERE window_start < now() - INTERVAL '1 day';
  END IF;

  RETURN v_count > p_max;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- SECURITY DEFINER functions are executable by PUBLIC by default, which would
-- let anyone with the anon key inflate counters for arbitrary keys (i.e. lock
-- other people out). Only the server, via the service role, may call it.
REVOKE EXECUTE ON FUNCTION hit_rate_limit(TEXT, INTEGER, INTEGER) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION hit_rate_limit(TEXT, INTEGER, INTEGER) TO service_role;

-- ==========================================================================
-- supabase/migrations/030_protect_subscription_tier.sql
-- ==========================================================================

-- The settings API no longer accepts subscription_tier, but the
-- "Users can manage own settings" RLS policy is FOR ALL, so anyone holding a
-- Supabase user JWT could still PATCH user_settings through PostgREST and
-- upgrade themselves. sync_frequency_minutes needs the same protection: the
-- cron uses it for free-tier users, so writing 1 there is an upgrade too.
-- Only the service role (the app's server code) or a direct SQL session may
-- change either column.

CREATE OR REPLACE FUNCTION protect_billing_columns()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  -- auth.role() is 'anon' / 'authenticated' for PostgREST user requests,
  -- 'service_role' for the server, and NULL for direct SQL.
  IF COALESCE(auth.role(), '') NOT IN ('anon', 'authenticated') THEN
    RETURN NEW;
  END IF;

  IF TG_OP = 'INSERT' THEN
    NEW.subscription_tier := 'free';
    NEW.sync_frequency_minutes := NULL;
  ELSIF NEW.subscription_tier IS DISTINCT FROM OLD.subscription_tier
     OR NEW.sync_frequency_minutes IS DISTINCT FROM OLD.sync_frequency_minutes THEN
    RAISE EXCEPTION 'subscription_tier and sync_frequency_minutes can only be changed by the server'
      USING ERRCODE = '42501';
  END IF;

  RETURN NEW;
END;
$$;

-- Named to sort before 009's tier trigger, so on INSERT the forced 'free'
-- is what that trigger derives sync_frequency_minutes from.
DROP TRIGGER IF EXISTS a_protect_billing_columns ON user_settings;
CREATE TRIGGER a_protect_billing_columns
  BEFORE INSERT OR UPDATE ON user_settings
  FOR EACH ROW EXECUTE FUNCTION protect_billing_columns();

-- ==========================================================================
-- supabase/migrations/031_sender_block_requires_no_approvals.sql
-- ==========================================================================

-- A sender the user approves must never be auto-blocked.
--
-- update_sender_reputation() set is_blocked once rejection_count reached 2,
-- regardless of approvals. Senders that attach two PDFs per email (invoice +
-- duplicate/receipt) collect a rejection every time the user keeps one copy
-- and rejects the other, so a sender with 12 approvals ended up both trusted
-- and blocked — and the auto-decision pipeline checks blocked first, so every
-- new invoice from it was silently auto-rejected and no notification was sent.
--
-- Blocking now requires that the user has never approved anything from the
-- sender. Existing rows are recomputed so currently-blocked senders with
-- approvals are unblocked immediately.

CREATE OR REPLACE FUNCTION update_sender_reputation()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO sender_reputation (
    user_id,
    sender_domain,
    approval_count,
    rejection_count,
    reputation_score,
    is_trusted,
    is_blocked,
    last_interaction,
    updated_at
  )
  VALUES (
    NEW.user_id,
    NEW.sender_domain,
    CASE WHEN NEW.action = 'approved' THEN 1 ELSE 0 END,
    CASE WHEN NEW.action = 'rejected' THEN 1 ELSE 0 END,
    CASE WHEN NEW.action = 'approved' THEN 1 ELSE -1 END,
    false,
    false,
    NOW(),
    NOW()
  )
  ON CONFLICT (user_id, sender_domain)
  DO UPDATE SET
    approval_count = sender_reputation.approval_count +
      CASE WHEN NEW.action = 'approved' THEN 1 ELSE 0 END,
    rejection_count = sender_reputation.rejection_count +
      CASE WHEN NEW.action = 'rejected' THEN 1 ELSE 0 END,
    reputation_score = (sender_reputation.approval_count +
      CASE WHEN NEW.action = 'approved' THEN 1 ELSE 0 END) -
      (sender_reputation.rejection_count +
      CASE WHEN NEW.action = 'rejected' THEN 1 ELSE 0 END),
    is_trusted = (sender_reputation.approval_count +
      CASE WHEN NEW.action = 'approved' THEN 1 ELSE 0 END) >= 3,
    is_blocked = (sender_reputation.rejection_count +
      CASE WHEN NEW.action = 'rejected' THEN 1 ELSE 0 END) >= 2
      AND (sender_reputation.approval_count +
      CASE WHEN NEW.action = 'approved' THEN 1 ELSE 0 END) = 0,
    last_interaction = NOW(),
    updated_at = NOW();

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

UPDATE sender_reputation
SET is_blocked = (rejection_count >= 2 AND approval_count = 0)
WHERE is_blocked IS DISTINCT FROM (rejection_count >= 2 AND approval_count = 0);
